import { getNodes, getNodeHistory } from './proxies/node'
import {
  createTunnel,
  getProxyList,
  getProxyNodes,
  updateProxy,
  deleteProxy,
  toggleProxy,
  getProxyConfig,
  getFreePort,
  batchOperateProxies,
  getProxyStats,
  reloadProxies,
} from './proxies/proxy'
import {
  forget,
  getBroadcast,
  getHitokoto,
  getTrafficTrend,
  getUserGroups,
  getUserInfo,
  getUserTraffic,
  login,
  logout,
  register,
  sendEmailCode,
  sendSmsCode,
  sign,
  getSoftwares,
  getDownloadSources,
  getSoftwareVersions,
  getProducts,
  buyProduct,
  updateUsername,
  updateNickname,
  updateAvatarUpload,
  updateAvatarQQ,
  updateAvatarCravatar,
  updatePassword,
  submitRealname,
  resetToken,
  checkPaymentStatus,
  getHomeStats,
  redeemCode,
  getRedeemRecords,
} from './user/user'
import {
  getUserList,
  updateUser,
  toggleUser,
  getNodeList,
  createNode,
  updateNode,
  deleteNode,
  toggleNode,
  getProxyList as getAdminProxyList,
  updateProxy as updateAdminProxy,
  deleteProxy as deleteAdminProxy,
  toggleProxy as toggleAdminProxy,
  banProxy,
  getProductList as getAdminProductList,
  createProduct,
  updateProduct,
  deleteProduct,
  getProductKinds,
  createProductKind,
  updateProductKind,
  deleteProductKind,
  getProductGrants,
  getGrantTargets,
  createProductGrant,
  updateProductGrant,
  deleteProductGrant,
  getSellableProductKinds,
  getSoftwareList as getAdminSoftwareList,
  createSoftware,
  updateSoftware,
  deleteSoftware,
  createSoftwareVersion,
  deleteSoftwareVersion,
  getSoftwareVersions as getAdminSoftwareVersions,
  getSystemSettings,
  getGroupList,
  createGroup,
  updateGroup,
  deleteGroup,
  getDownloadSources as getAdminDownloadSources,
  createDownloadSource,
  updateDownloadSource,
  deleteDownloadSource,
  updateSmtpSetting,
  updateSetting,
  updateSmsSetting,
  getSmtpSetting,
  getSmsSetting,
  updateSoftwareVersion,
  getBroadcastList,
  createBroadcast,
  updateBroadcast,
  deleteBroadcast,
  toggleBroadcastTop,
  getRedeemCodeList,
  createRedeemCodes,
  exportRedeemCodes,
  updateRedeemCodeStatus,
  deleteRedeemCode,
} from './admin/admin'

const userApi = {
  login,
  register,
  forget,
  sendEmailCode,
  sendSmsCode,
  getHitokoto,
  logout,
  getTrafficTrend,
  getBroadcast,
  getUserInfo,
  getUserTraffic,
  sign,
  getNodeHistory,
  getNodes,
  getUserGroups,
  createTunnel,
  getProxyList,
  getProxyNodes,
  updateProxy,
  deleteProxy,
  toggleProxy,
  getProxyConfig,
  getFreePort,
  batchOperateProxies,
  getProxyStats,
  reloadProxies,
  getSoftwares,
  getDownloadSources,
  getSoftwareVersions,
  getProducts,
  buyProduct,
  updateUsername,
  updateNickname,
  updateAvatarUpload,
  updateAvatarQQ,
  updateAvatarCravatar,
  updatePassword,
  submitRealname,
  resetToken,
  checkPaymentStatus,
  getHomeStats,
  // 兑换码
  redeemCode,
  getRedeemRecords,
}

const adminApi = {
  // 用户管理
  getUserList,
  updateUser,
  toggleUser,
  // 节点管理
  getNodeList,
  createNode,
  updateNode,
  deleteNode,
  toggleNode,
  // 代理管理
  getProxyList: getAdminProxyList,
  updateProxy: updateAdminProxy,
  deleteProxy: deleteAdminProxy,
  toggleProxy: toggleAdminProxy,
  banProxy,
  // 产品管理
  getProductList: getAdminProductList,
  createProduct,
  updateProduct,
  deleteProduct,
  // 商品类型管理
  getProductKinds,
  createProductKind,
  updateProductKind,
  deleteProductKind,
  // 发放规则管理
  getProductGrants,
  getGrantTargets,
  createProductGrant,
  updateProductGrant,
  deleteProductGrant,
  // 可售商品类型（用户组 + 商品类型）
  getSellableProductKinds,
  // 软件管理
  getSoftwareList: getAdminSoftwareList,
  createSoftware,
  updateSoftware,
  deleteSoftware,
  createSoftwareVersion,
  deleteSoftwareVersion,
  getSoftwareVersions: getAdminSoftwareVersions,
  // 系统设置
  getSystemSettings,
  getSmtpSetting,
  getSmsSetting,
  updateSetting,
  updateSmtpSetting,
  updateSmsSetting,
  // 用户组管理
  getGroupList,
  createGroup,
  updateGroup,
  deleteGroup,
  // 下载源管理
  getDownloadSources: getAdminDownloadSources,
  createDownloadSource,
  updateDownloadSource,
  deleteDownloadSource,
  updateSoftwareVersion,
  // 通知管理
  getBroadcastList,
  createBroadcast,
  updateBroadcast,
  deleteBroadcast,
  toggleBroadcastTop,
  // 兑换码管理
  getRedeemCodeList,
  createRedeemCodes,
  exportRedeemCodes,
  updateRedeemCodeStatus,
  deleteRedeemCode,
}
export { userApi, adminApi }
