name: Vue项目手动构建 (Node.js 22 + pnpm)

on:
  workflow_dispatch:
    inputs:
      build_env:
        description: '构建环境'
        required: true
        default: 'production'
        options:
          - production
          - development
      output_dir:
        description: '输出目录'
        required: false
        default: 'dist'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Node.js 22环境
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: 安装pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: false

      - name: 清除node_modules
        run: rm -rf node_modules

      - name: 安装依赖
        run: |
          pnpm install --frozen-lockfile --prod=false
          # 使用WASM版本的Rollup作为跨平台解决方案
          pnpm add @rollup/rollup-wasm --no-save || true
        env:
          NODE_OPTIONS: --openssl-legacy-provider
          PNPM_FORCE: true

      - name: 构建项目
        run: |
          if [ "${{ github.event.inputs.build_env }}" = "development" ]; then
            pnpm run build:dev || pnpm run build
          else
            NODE_ENV=production pnpm run build
          fi
        env:
          NODE_V8_COMPAT: 1

      - name: 验证输出目录
        id: check_output
        run: |
          dir="${{ github.event.inputs.output_dir || 'dist' }}"
          if [ ! -d "$dir" ]; then
            echo "::warning::构建目录不存在: $dir"
            mkdir -p dist
            dir="dist"
          fi
          echo "output_dir=$dir" >> $GITHUB_OUTPUT
          ls -la "$dir"

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: vue-build-${{ github.event.inputs.build_env }}-node22-pnpm
          path: ${{ steps.check_output.outputs.output_dir }}/
          compression-level: 5
          retention-days: 1
