name: Vue项目手动构建 (Node.js 22)

on:
  workflow_dispatch:
    inputs:
      build_env:
        description: '构建环境'
        required: true
        default: 'production'
        options:
          - production
          - development
      output_dir:
        description: '输出目录'
        required: false
        default: 'dist'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置Node.js 22环境
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org/'
          
      - name: 清除旧依赖
        run: |
          rm -rf node_modules package-lock.json
          echo "旧依赖已清除"
          
      - name: 安装依赖（解决可选依赖问题）
        run: |
          npm install --no-audit --production=false --force
          # 手动安装Rollup二进制依赖（Linux x64）
          if [ "$(uname -m)" == "x86_64" ]; then
            if [ ! -d "node_modules/@rollup/rollup-linux-x64-gnu" ]; then
              npm install @rollup/rollup-linux-x64-gnu --no-save
              echo "已手动安装Rollup二进制"
            fi
          fi
          # 验证依赖安装
          npm list rollup
        env:
          NODE_OPTIONS: --openssl-legacy-provider
          npm_config_force: true
          
      - name: 构建项目
        run: |
          if [ "${{ github.event.inputs.build_env }}" == "development" ]; then
            npm run build:dev || npm run build
          else
            npm run build
          fi
        env:
          NODE_ENV: ${{ github.event.inputs.build_env }}
          NODE_V8_COMPAT: 1  # 启用V8兼容模式
          
      - name: 验证输出目录
        run: |
          dir=$(echo ${{ github.event.inputs.output_dir }})
          if [ -d "$dir" ]; then
            echo "构建目录存在: $dir"
            ls -la "$dir"
          else
            echo "警告: 构建目录不存在，使用默认dist目录"
            mkdir -p dist
          fi
          
      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: vue-build-${{ github.event.inputs.build_env }}-node22
          path: ${{ github.event.inputs.output_dir }}/
          compression-level: 5  # 降低压缩级别，加速Node.js 22构建
          retention-days: 14    # 产物保留14天
